version: "3.7"

services:
  database_project:
    image: postgres
    container_name: database_project
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=bruno
      - POSTGRES_DB=database
      
      
      
    
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: project
    ports:
      - 3333:3333
    volumes:  
      - .:/usr/app
    
volumes:
  pgdata:
    driver: local

 